### ISSUE TITLE
Setup support for localisation

### ISSUE THREAD

**Issue by artehe** [stayintarkov/SIT.Manager.Avalonia#10]
Something for the future and should be relatively easy to setup but just take some time to convert all the initial strings over.

This guide should explain how we need to do it: https://docs.avaloniaui.net/docs/guides/implementation-guides/localizing

**Comment by Plootie** [comment]
Oh wow that's much better than the idea i had for doing this @~@ definitely something I'd like to get into this. We'll need to source translations from somewhere once the framework for doing this is in place

**Comment by J0nathan550** [comment]
I will try to look more forward into it 😄

**Comment by J0nathan550** [comment]
I dig up a little bit, and this thing is not what we need really. Problem accurs when you want to change the language, in this project I repeat the same tutorial (from Avalonia), and problem is that {x:Static} doesn't really want to change the language, besides from the very begin of the program. It changes text only after restart. Need to dig more. Probably better to do model with all of constant strings.

**Comment by J0nathan550** [comment]
This one is interesting and also works in Avalonia but with slightly different approach.
https://github.com/timunie/Tims.Avalonia.Samples/tree/main

**Comment by artehe** [comment]
> I dig up a little bit, and this thing is not what we need really. Problem accurs when you want to change the language, in this project I repeat the same tutorial (from Avalonia), and problem is that {x:Static} doesn't really want to change the language, besides from the very begin of the program. It changes text only after restart. Need to dig more. Probably better to do model with all of constant strings.

That's a fair point it wouldn't exactly be dynamic, it'd just use whatever dictionary it had available or fall back on english for that method.

> This one is interesting and also works in Avalonia but with slightly different approach. https://github.com/timunie/Tims.Avalonia.Samples/tree/main

The basic idea is the same but would probably work better if we wanted to have a language selection in the settings somewhere. I'd probably say use this if you wanted to work on it.

**Comment by J0nathan550** [comment]
> > I dig up a little bit, and this thing is not what we need really. Problem accurs when you want to change the language, in this project I repeat the same tutorial (from Avalonia), and problem is that {x:Static} doesn't really want to change the language, besides from the very begin of the program. It changes text only after restart. Need to dig more. Probably better to do model with all of constant strings.
> 
> That's a fair point it wouldn't exactly be dynamic, it'd just use whatever dictionary it had available or fall back on english for that method.
> 
> > This one is interesting and also works in Avalonia but with slightly different approach. https://github.com/timunie/Tims.Avalonia.Samples/tree/main
> 
> The basic idea is the same but would probably work better if we wanted to have a language selection in the settings somewhere. I'd probably say use this if you wanted to work on it.

I will try to use Dynamic Resource, but shi. MVVM is a pain in the ass sometimes.

**Comment by J0nathan550** [comment]
Here is progress of the Translation, what remains is to literally create strings for everything 😄 
https://youtu.be/UD6dMg0-cSU
