### ISSUE TITLE
Remove the need for the extra files flag in the Mods Page

### ISSUE THREAD

**Issue by artehe** [stayintarkov/SIT.Manager.Avalonia#110]
The "Required Extra Files" flag for modding in the manager, it seems like a lot of people don't really understand the process.

So I think the best approach would be to include the dependecy dll into the https://github.com/stayintarkov/SIT-Mod-Ports for those that require any porting but others that don't need can just be linked to.

Can replace the "Required Extra Files" flag with a section of dependencies that either links to the reuqired download files or the other required mod in the master list. Then the manager can just install all of these dependencies as well.

**Comment by Plootie** [comment]
@artehe Given the impending changes to mods do we want to close this issue?

**Comment by artehe** [comment]
Ye that probably makes sense
