### ISSUE TITLE
mark old manager as discontinued

### ISSUE THREAD

**Issue by Beat2er** [stayintarkov/SIT.Manager.Avalonia#122]
Hi, are we planning on marking https://github.com/stayintarkov/SIT.Manager as discontinued, so new players are linked to the new manager?

**Comment by Plootie** [comment]
Currently all links at least on the discord now point to this manager and there are plans to archive the previous manager when we make our next release which will probably be in the next couple of days

**Comment by Plootie** [comment]
Old manager repo is now archived 👍
