### ISSUE TITLE
[Install Page] Configure percent calculating wrong

### ISSUE THREAD

**Issue by J0nathan550** [stayintarkov/SIT.Manager.Avalonia#129]
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/88881607/c17dce64-8f59-48ec-a8ed-ac5198a89d9b)

**Comment by artehe** [comment]
Does this happen when selecting mega as the download mirror?

**Comment by J0nathan550** [comment]
Yes

**Comment by artehe** [comment]
Cool thought so this PR will fix it then 😄

**Comment by J0nathan550** [comment]
> Cool thought so this PR will fix it then 😄
> 
> Feel free to play round with it and see if there's some more issues with it that need fixing

No problem I always do install of tarkov from zero when new version releases to test everything.
