### ISSUE TITLE
Server console issues

### ISSUE THREAD

**Issue by Plootie** [stayintarkov/SIT.Manager.Avalonia#137]
Ended up down a bit of a rabbit hole on this. If you clear the server console, leave the server page and re-enter it will copy a bunch of text back into the console.

Also from what I can see there is nothing stopping the server console collection filling with entries, only the cached entries.

It might be worth rewriting the entire console system instead of trying to bandage it

**Comment by artehe** [comment]
It's worked pretty well for me every time I've used it.

At this point don't even think there's much we need to do to it, unless there's some glaring issues I'm missing

**Comment by artehe** [comment]
Gonna close this for now as I think everything is fine?
