### ISSUE TITLE
how to debug/attach debugger in rider without modifications

### ISSUE THREAD

**Issue by Beat2er** [stayintarkov/SIT.Manager.Avalonia#154]
Hi there, I'm really curious how you all are approaching this or how my env is setup poorly.
When I try to debug SIT.Manager.Desktop (the wrapper), i just get this error (At leat one error occured)
```cmd
C:/Users/Username/RiderProjects/SIT.Manager.Avalonia/SIT.Manager.Desktop/bin/Debug/net8.0/win-x64/SIT.Manager.exe 
Mindestens ein Fehler ist aufgetreten.
```
_Edit: in Rider EAP: `One or more errors occurred. (One or more errors occurred. (CLR load callback is already in error state. Error HRESULT E_FAIL has been returned from a call to a COM component. The error code is E_FAIL, or EFail, or 0x80004005.))`_

Ok, this is fine, cause the way to go is to start SIT.Manager.Desktop normally and then attach the debugger
![grafik](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/53951641/6aec9876-4861-41aa-aa69-d10b92a49d85)
Then `Attach wit .NET Debugger`...
The debugger can find the breakpoints, in contraire to attaching to an unrelated process.
But all debugging features stay unpopulated:
![grafik](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/53951641/ef04d3e4-9050-4d46-8bb7-598dbec3c666)
I can't seem to get any breakpoints to work.

in VS2022 all kind of works out of the box

My workaround for local work is to change SIT.Manager to be a WinExe and add a Program.cs

What am I doing wrong? Can we document this a little further?

The error seems to be known: https://www.reddit.com/r/Jetbrains/comments/100nc32/where_is_the_error_hiding_in_rider/
(It seems to be project specific)
Are you all using VS2022?

**Comment by J0nathan550** [comment]
Hello, in order to properly work in our project you need to install VS2022 with C# dependency.
I never worked with Rider and not sure if Avalonia framework supports working with this IDE.
It's better to use VS2022.

**Comment by J0nathan550** [comment]
I also suggest you to look at the documentation of the Avalonia in order to start.
https://avaloniaui.net/

**Comment by artehe** [comment]
Can't say I've ever used Rider but as J0nathan550 said Avalonia should work nicely with it.

This is probably that page which will help you with it: https://docs.avaloniaui.net/docs/reference/jetbrains-rider-ide/jetbrains-rider-setup
