### ISSUE TITLE
Refactor and fix IDE comments and warnings.

### ISSUE THREAD

**Issue by J0nathan550** [stayintarkov/SIT.Manager.Avalonia#165]
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/88881607/9533f1c4-b117-4ec3-8cea-bc18a7441b34)
Would be great to use new C# features and fix warnings to fix possible errors. (Also maybe optimize a little the program (not sure about this one)).

**Comment by Plootie** [comment]
I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read

**Comment by J0nathan550** [comment]
> I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read

at least is suggest to do caching in some areas.

**Comment by J0nathan550** [comment]
Also when we will fix the JSON model classes like bosses and github related classes with new .NET 8 Json it will benefit with loading speed of classes since .NET 8 improved JSON.

**Comment by artehe** [comment]
> I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read

Ye sometimes the new makes it worse rather than better 😓 in most places it is understandable though.

> > I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read
> 
> at least is suggest to do caching in some areas.

Things are starting to get cached more but it's more a case of doing it when and where it's needed rather than just doing caching for the sake of caching.


Overall I'm not strictly against resolving most of the warnings/messages Visual Studio is putting out, some of them are not helpful or more accuratly not relevant for what we are doing so would probably make more sense to disable those if it is that much of a bother.

What I would object to though is having them all in one PR as while Visual Studio is helpful sometimes some of the things it tells you to fix can actually just cause issues. So I'd suggest doing things in a targeted manner, like the first one which would probably remove most of these would be the JSON models BaseLocation and GiteaRelease you deal with them 95% of the things the IDE is saying will go away.

**Comment by J0nathan550** [comment]
> > I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read
> 
> Ye sometimes the new makes it worse rather than better 😓 in most places it is understandable though.
> 
> > > I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read
> > 
> > 
> > at least is suggest to do caching in some areas.
> 
> Things are starting to get cached more but it's more a case of doing it when and where it's needed rather than just doing caching for the sake of caching.
> 
> Overall I'm not strictly against resolving most of the warnings/messages Visual Studio is putting out, some of them are not helpful or more accuratly not relevant for what we are doing so would probably make more sense to disable those if it is that much of a bother.
> 
> What I would object to though is having them all in one PR as while Visual Studio is helpful sometimes some of the things it tells you to fix can actually just cause issues. So I'd suggest doing things in a targeted manner, like the first one which would probably remove most of these would be the JSON models BaseLocation and GiteaRelease you deal with them 95% of the things the IDE is saying will go away.

Not really, it's saying to change the variable names and use JSON attribute as how class looked before. It will work the same.

**Comment by Plootie** [comment]
> > > I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read
> > 
> > 
> > Ye sometimes the new makes it worse rather than better 😓 in most places it is understandable though.
> > > > I'd hold off on tackling thus until all major pull requests are out the way. I also disagree with microsoft's push for certain features such as always using the shorthand `new` in areas where it makes it difficult to read
> > > 
> > > 
> > > at least is suggest to do caching in some areas.
> > 
> > 
> > Things are starting to get cached more but it's more a case of doing it when and where it's needed rather than just doing caching for the sake of caching.
> > Overall I'm not strictly against resolving most of the warnings/messages Visual Studio is putting out, some of them are not helpful or more accuratly not relevant for what we are doing so would probably make more sense to disable those if it is that much of a bother.
> > What I would object to though is having them all in one PR as while Visual Studio is helpful sometimes some of the things it tells you to fix can actually just cause issues. So I'd suggest doing things in a targeted manner, like the first one which would probably remove most of these would be the JSON models BaseLocation and GiteaRelease you deal with them 95% of the things the IDE is saying will go away.
> 
> Not really, it's saying to change the variable names and use JSON attribute as how class looked before. It will work the same.

It might not seem like it but some suggestions can actually break things (first hand experience)

Either way a lot of code is going to replaced when all pull requests are closed out and they won't be up to date so my point stands that it's probably best to hold off

**Comment by artehe** [comment]
The main source of compiler noise left comes from the [BaseLocation.cs](https://github.com/stayintarkov/SIT.Manager.Avalonia/blob/master/SIT.Manager/Models/BaseLocation.cs) file, at least after #207 is merged.

So I'm gonna close this now. If you want to tidy up that file please feel free, it'd also probably be an idea at the same time to give some love to the whole LocationEditorView as that's where it gets used but it doesn't seem to work that well :/
