### ISSUE TITLE
[feature request] restart server when hitting "Start Server and Connect"

### ISSUE THREAD

**Issue by kapdon** [stayintarkov/SIT.Manager.Avalonia#216]
seeing this issue pop up in the support channel. the start server and connect button only checks if server is up, so when debugging people's set ups they press this button but in fact have not restarted the server.

I think this is a simple addition that'll add a few seconds to game boot time but save a lot of headaches.

**Comment by artehe** [comment]
Not 100% keen on letting people restart the server from the play page, think this should always be something they go out of their way to do but we hide the start server button on the play page now if the server is running which might help?
