### ISSUE TITLE
Unable to determine available SIT versions.

### ISSUE THREAD

**Issue by CapitalGrin** [stayintarkov/SIT.Manager.Avalonia#218]
manager version: 2.2.2404.2719
"Unable to determine available SIT versions" when tring to install SIT with the manager,
maybe it's because official EFT version is now 0.14.6.0.29862, and client mod won't fit the latest verision.
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/109933411/dc494e0a-8221-443c-9b91-d4d038104121)
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/109933411/0e194298-412a-44d3-8f7c-79b8e544f980)

I'm sorry if I have asked silly question, How can I download the available version of game and install SIT for it?

**Comment by Saitamaone** [comment]
i have the same problem i have try for 2 hour to go around it but it doesnt work. I think we need to wait

**Comment by artehe** [comment]
Should be sorted now, was a mistake in the mirrors list we provide
