### ISSUE TITLE
error acquire the patcher for eft 

### ISSUE THREAD

**Issue by Saitamaone** [stayintarkov/SIT.Manager.Avalonia#220]
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/44630984/5f2325ee-2b6d-402a-b69b-3a7d1fc9b76b)

**Comment by Plootie** [comment]
Still encountering this? I believe we fixed this earlier today and just want confirmation before I close it out

**Comment by Saitamaone** [comment]
its working now thks
