### ISSUE TITLE
SIT mods incompatible with latest release 

### ISSUE THREAD

**Issue by warrenjayv** [stayintarkov/SIT.Manager.Avalonia#229]
hello, just wanted to inform that to get mods such as SAIN to work, you have to downgrade to **StayInTarkov.Client-1.10.8854.18454**

https://github.com/stayintarkov/SIT.Manager.Avalonia/releases/tag/2.2.2404.2719

**Comment by artehe** [comment]
We are aware, mods are just in a bit of an odd place at the moment. You'll find up to date versions of the currently ported mods in the discord while things get sorted out.
