### ISSUE TITLE
Bookmark user list bug

### ISSUE THREAD

**Issue by arnobru** [stayintarkov/SIT.Manager.Avalonia#233]
Hello and congrats on the cool project :)

The latest release mostly fixed the bookmark feature, but I noticed another small bug though.

Once logged in to my bookmarked server in the manager, all detected users on the server are listed in the "Bookmarks" tab, as normal. But from there, switching between the "Bookmarks" tab and the "Direct connect" tab results in my username being duplicated once in the "Bookmarks" tab. Switching, say, 5 times between those tabs result in my username being listed 5 times.

So not really a big issue, but I thought you might be interested to know.

**Comment by artehe** [comment]
No problem we much prefer it when people let us know of issues that exist.

For this one PR #231 should resolve this when it gets merged.
