### ISSUE TITLE
[Bug] Localization in some pages doesn't translate some keys when localization is changed.

### ISSUE THREAD

**Issue by J0nathan550** [stayintarkov/SIT.Manager.Avalonia#235]
There are more pages. This one is just an simple example.

https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/88881607/689fed0e-8fd3-4412-a839-8fc1dc63a624

**Comment by artehe** [comment]
If there are others let me know where they are and I can fix them.

It could always be that localisation strings are missing for them as well

**Comment by J0nathan550** [comment]
They are bot missing they literally lack of updating. We need to raise "localisation update" event in order to change strings

**Comment by J0nathan550** [comment]
They are bot missing they literally lack of updating. We need to raise "localisation update" event in order to change strings
