### ISSUE TITLE
Manager shows ALL accounts on connected server

### ISSUE THREAD

**Issue by Ketris** [stayintarkov/SIT.Manager.Avalonia#247]
When adding any server to the Bookmarks page, you are then able to view a complete list of every account name on the server. This seems insecure and (hopefully) unintentional.

**Comment by Ketris** [comment]
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/726660/1d5531a3-d534-45a0-b6c2-59c96cdaf197)

**Comment by artehe** [comment]
PR #252 will tidy this up a bit.

> When adding any server to the Bookmarks page, you are then able to view a complete list of every account name on the server. This seems insecure and (hopefully) unintentional.

It's semi intentional, to provide an easier way to connect/save character logins (mainly as I couldn't think of a nicer way of doing it when I made it). In terms of security it's not exactly that bad, the server itself already does worse things.
