### ISSUE TITLE
Solve binding error

### ISSUE THREAD

**Issue by Plootie** [stayintarkov/SIT.Manager.Avalonia#25]
I've noticed this for awhile but ignored it as it seems to not affect anything we're doing but I'd really like to find and solve this for the sake of not having rouge errors in the project. At runtime the error `[Binding]Error in binding to 'Avalonia.Controls.ColumnDefinition'.'Width': 'Null value in expression '{empty}' at '$self.TemplatedParent'.'(ColumnDefinition #7689721)` is thrown. I believe this is from the color picker

**Comment by artehe** [comment]
Could be...

If not this color picker still might be something to replace as I'm stupid and added a package to get access to a color picker completely forgetting that Avalonia has a color picker built in which we should probably use instead🙃
