### ISSUE TITLE
Manager not waiting for server when CAL not set

### ISSUE THREAD

**Issue by Plootie** [stayintarkov/SIT.Manager.Avalonia#40]
With the introduction of #28 we have broken the quick play button when close after launch isn't set. It will immediately attempt to connect to the server and throw a connection error. I don't know how much of this logic will be altered by #38 so it might be better to fix this now

**Comment by artehe** [comment]
Whoops, I may not have thought about that case.

**Comment by artehe** [comment]
I'll update this pr to fix it as they're closely related enough
