### ISSUE TITLE
File Extraction doesn't update notification

### ISSUE THREAD

**Issue by artehe** [stayintarkov/SIT.Manager.Avalonia#42]
Appears that when extracting a file using the FileService.ExctractArchive method the action notification which should display at the bottom of the screen doesn't update after it appears.

I don't entirely know why, but then I've never been keen on how I made the action notification service anyway so possibly something to do with how it works.

**Comment by Plootie** [comment]
This might be my doing. The changes I made to the extraction code means it sometimes extracts entire folders in one operation which will break it in 2 ways. 1 It will extract an entire folder before updating (therefor it will only update once the entire folder is extracted) and secondly it will treat this operation as only one file being updated despite there possibly being thousands of files in the folder we just extracted
